# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ayKiTtO5NMEemJ2Y2G6xrbwAybGUm1aq

# EDA on Loan Banking_Dataset
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
from IPython.display import display

df = pd.read_csv('/content/drive/MyDrive/Banking/Banking.csv')

df.head(5)

df.shape

df.info()

# generate descriptive statistics

df.describe()

df['Estimated Income'].min()

# convert from numerical and categorical data

bins = [0,100000,300000, float('inf')]
labels = ['Low', "Med", "High"]
# create income bin
df['Income Band'] = pd.cut(df['Estimated Income'], bins=bins, labels=labels, right=False)

df['Income Band'].value_counts().plot(kind='bar')

# examin the distribution of unique categories

categorical_cols = ["BRId", "GenderId", "IAId", "Amount of Credit Cards","Nationality", "Occupation", "Fee Structure", "Loyalty Classification", "Properties Owned", "Risk Weighting", "Income Band" ]

for col in categorical_cols:
    print(f"Values Counts for '{col}':")
    display(df[col].value_counts())

for i, predictor in enumerate(df):
  plt.figure(i)
  sns.countplot(data=df, x=predictor, hue="GenderId")

"""Bivariate Ananlysis -"""

for i, predictor in enumerate(df[["BRId", "GenderId", "IAId", "Amount of Credit Cards","Nationality", "Occupation", "Fee Structure", "Loyalty Classification", "Properties Owned", "Risk Weighting", "Income Band" ]]):
  plt.figure(i)
  sns.countplot(data=df, x=predictor, hue="Nationality")

# histogram of value counts

for col in categorical_cols:
  if col == "Occupation":
    continue
  plt.figure(figsize=(8,4))
  # Corrected the function name from histoplot to histplot
  sns.histplot(df[col])
  plt.title("Histogram of Occupation Count")
  plt.xlabel(col)
  plt.ylabel("Count")
  plt.show()

"""Numerical Analysis- anaylyse the other numerical columns"""

numerical_cols = ['Estimated Income', 'Superannuation Savings', 'Credit Card Balance', 'Bank Loans', 'Bank Deposits','Checking Accounts', 'Saving Accounts', 'Foreign Currency Account', 'Business Lending']

plt.figure(figsize=(15, 10))
for i, col in enumerate(numerical_cols):
    plt.subplot(4,3,i+1)
    sns.histplot(df[col], kde=True)
    plt.title(col)
plt.show()

"""HeatMaps - correlation between numerical attributes

Banking deposits have high correlation with checking account and savings account--> strong posistive correlation.
**Foreigh curr account ** --> strong positive correlation. means that customers that hold large funds in one  accounts type will mostly hold large amounts accross vaious account types as well.
Credit card usage to
"""

numerical_cols = ['Estimated Income', 'Superannuation Savings', 'Credit Card Balance', 'Bank Loans', 'Bank Deposits','Checking Accounts', 'Saving Accounts', 'Foreign Currency Account', 'Business Lending']

correlation_matrix = df[numerical_cols].corr()

plt.figure(figsize=(10, 8))
sns.heatmap(correlation_matrix, annot=True, cmap='crest', fmt = '.2f')
plt.title('Correlation Matrix')
plt.show()



"""Insights of EDA



1.   The strongests positive correlation occur among bank deposits with "checking accounts", Savings accounts and foreighn currency account indication that customers who maintain high balances in one account type often hold substantial amount of fund accross various accounts as well
2.   List item


"""





